UPDATE EMPLOYEES SET First_Name= ?, 
                     Last_Name = ?, 
                     Email = ?,
                     Phone = ?,
                     Department = ?, 
                     Designation = ?, 
                     Salary = ?, 
                     Joining_Date = ? 
        WHERE Employee_ID = ? 
